package ahorcado.gui;

import java.util.Scanner;
import pasapalabra.EstudiaIntentos;

public class El_Ahorcado extends javax.swing.JFrame {
    Scanner entradas = new Scanner(System.in);
    static EstudiaIntentos objeto = new EstudiaIntentos();    
    static char ch;
    static int contador = 0;
    VolverAJugar dialog = new VolverAJugar(this, true);
    public static String palabra = "";
    public static String palabraOculta = "";
    public static long tiempoInicial = 0;
            
    /**
     * Creates new form El_Ahorcado
     */
    public El_Ahorcado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPalabra = new javax.swing.JLabel();
        labelLetra = new javax.swing.JLabel();
        textoPalabra = new javax.swing.JTextField();
        textoLetra = new javax.swing.JTextField();
        comprobarLetra = new javax.swing.JButton();
        intentosPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        intentos = new javax.swing.JTextArea();
        statusPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusText = new javax.swing.JTextArea();
        jugarBottom = new javax.swing.JButton(new javax.swing.ImageIcon( new javax.swing.ImageIcon(getClass().getResource( "/ahorcado/gui/playbutton2.png")).getImage().getScaledInstance( 16, 16, java.awt.Image.SCALE_SMOOTH)));
        jMenuBar1 = new javax.swing.JMenuBar();
        aplicacionMenu = new javax.swing.JMenu();
        volverEmpezarMenu = new javax.swing.JMenuItem();
        salirMenu = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        infoMenu = new javax.swing.JMenuItem();
        comoJugarMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Ahorcado");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/gui/Hangman_Game.png")).getImage()
        );

        labelPalabra.setText("Palabra:");

        labelLetra.setText("Introduce una letra/palabra:");

        textoPalabra.setBackground(new java.awt.Color(173, 238, 255));
        textoPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPalabraActionPerformed(evt);
            }
        });

        textoLetra.setBackground(new java.awt.Color(173, 238, 255));

        comprobarLetra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comprobarLetra.setForeground(new java.awt.Color(0, 204, 255));
        comprobarLetra.setText("Comprobar");
        comprobarLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobarLetraActionPerformed(evt);
            }
        });

        intentosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 255)), "Progreso"));

        intentos.setBackground(new java.awt.Color(172, 238, 255));
        intentos.setColumns(20);
        intentos.setRows(5);
        intentos.setBorder(null);
        jScrollPane1.setViewportView(intentos);

        javax.swing.GroupLayout intentosPanelLayout = new javax.swing.GroupLayout(intentosPanel);
        intentosPanel.setLayout(intentosPanelLayout);
        intentosPanelLayout.setHorizontalGroup(
            intentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        intentosPanelLayout.setVerticalGroup(
            intentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );

        statusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 255)), "Resultado"));

        statusText.setBackground(new java.awt.Color(173, 238, 255));
        statusText.setColumns(20);
        statusText.setRows(5);
        jScrollPane2.setViewportView(statusText);

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        jugarBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/gui/playbutton2.png"))); // NOI18N
        jugarBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarBottomActionPerformed(evt);
            }
        });

        aplicacionMenu.setText("Aplicación");

        volverEmpezarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        volverEmpezarMenu.setText("Volver a empezar");
        volverEmpezarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverEmpezarMenuActionPerformed(evt);
            }
        });
        aplicacionMenu.add(volverEmpezarMenu);

        salirMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        salirMenu.setText("Salir");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        aplicacionMenu.add(salirMenu);

        jMenuBar1.add(aplicacionMenu);

        ayudaMenu.setText("Ayuda");

        infoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        infoMenu.setText("Información");
        infoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMenuActionPerformed(evt);
            }
        });
        ayudaMenu.add(infoMenu);

        comoJugarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        comoJugarMenu.setText("Cómo jugar");
        comoJugarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoJugarMenuActionPerformed(evt);
            }
        });
        ayudaMenu.add(comoJugarMenu);

        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugarBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 42, Short.MAX_VALUE))
                            .addComponent(textoPalabra))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoLetra))
                        .addGap(31, 31, 31)
                        .addComponent(comprobarLetra))
                    .addComponent(intentosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPalabra)
                            .addComponent(labelLetra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jugarBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comprobarLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(intentosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprobarLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobarLetraActionPerformed
        // TODO add your handling code here:       
        String palabraIntento = textoLetra.getText();        
        ch = palabraIntento.charAt(0);
        textoLetra.setText("");
        if (palabraIntento.length()>1){
            if(!palabraIntento.equals(palabra)){
            intentos.setText(intentos.getText()+ "Esa no es la palabra\n");
            contador++;      
            } else {
                statusText.setText("La palabra era "+palabra+"\nEl numero de fallos acumulados es de "+contador+"\nEl tiempo empleado es de "+(System.currentTimeMillis()-tiempoInicial)/1000+" segundos");
                dialog.setVisible(true);
            }           
        } else {            
            if (!objeto.yaEstaEnPalabra(palabraOculta, ch)){
            palabraOculta = objeto.obtenerIntento(palabra, palabraOculta,ch);        
                if (!objeto.esCorrecta){
                    intentos.setText(intentos.getText()+"Lo siento, "+ch+" no está en la palabra.\n");
                    contador++;                    
                    statusText.setText(statusText.getText()+ch+" ");
                } else {                    
                    intentos.setText(intentos.getText()+"Bien! ");            
                }
            }        
            else {
                intentos.setText(intentos.getText()+ch+ " está ya en la palabra.\n");
            }           
            intentos.setText(intentos.getText()+palabraOculta+"\n");        
        }
        if(palabraOculta.equals(palabra)){            
            statusText.setText("La palabra era "+palabra+"\nEl numero de fallos acumulados es de "+contador+"\nEl tiempo empleado es de "+(System.currentTimeMillis()-tiempoInicial)/1000+" segundos");
            dialog.setVisible(true);
        }                
    }//GEN-LAST:event_comprobarLetraActionPerformed

    private void textoPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPalabraActionPerformed

    private void volverEmpezarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverEmpezarMenuActionPerformed
        // TODO add your handling code here:
        jugar();
    }//GEN-LAST:event_volverEmpezarMenuActionPerformed

    private void infoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMenuActionPerformed
        // TODO add your handling code here:
        informacion info = new informacion(this, true);
        info.setVisible(true);
    }//GEN-LAST:event_infoMenuActionPerformed

    private void comoJugarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoJugarMenuActionPerformed
        // TODO add your handling code here:
        comoJugar ayuda = new comoJugar(this, true);
        ayuda.setVisible(true);
    }//GEN-LAST:event_comoJugarMenuActionPerformed

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_salirMenuActionPerformed

    private void jugarBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarBottomActionPerformed
        // TODO add your handling code here:
        jugar();
    }//GEN-LAST:event_jugarBottomActionPerformed
       
    
    
    public static void jugar(){        
        textoLetra.setText("");
        intentos.setText("");
        statusText.setText("Letras falladas: ");
        contador=0;
        palabra = objeto.obtenerPalabra();
        palabraOculta = objeto.obtenerPalabraOculta(palabra);
        textoPalabra.setText(palabraOculta);
        tiempoInicial = System.currentTimeMillis();
    }
    
    public static void salir(){
        System.exit(1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(El_Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(El_Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(El_Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(El_Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
               
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new El_Ahorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aplicacionMenu;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenuItem comoJugarMenu;
    private static javax.swing.JButton comprobarLetra;
    private javax.swing.JMenuItem infoMenu;
    private static javax.swing.JTextArea intentos;
    private javax.swing.JPanel intentosPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JButton jugarBottom;
    private javax.swing.JLabel labelLetra;
    private javax.swing.JLabel labelPalabra;
    private javax.swing.JMenuItem salirMenu;
    private javax.swing.JPanel statusPanel;
    private static javax.swing.JTextArea statusText;
    private static javax.swing.JTextField textoLetra;
    private static javax.swing.JTextField textoPalabra;
    private javax.swing.JMenuItem volverEmpezarMenu;
    // End of variables declaration//GEN-END:variables
}
